### ISSUE TITLE
Fix Edge SVG not Bubbling Up Click Events

### ISSUE THREAD

**Issue by erichomanchuk** [fosterinteractive/mainspring#24]
When clicking on a svg's use in a button the event doesn't bubble up so in javascript the click event doesn't happen. Apply a css style to the use element.

svg use { pointer-events:none; }

https://connect.microsoft.com/IE/feedback/details/796745/mouse-events-are-not-delivered-at-all-anymore-when-inside-an-svg-a-use-is-removed-from-the-dom

**Comment by fosterinteractive** [comment]
Resolved in 0.3
